version: "3.1"

services:
    backend:
        build: .
        restart: unless-stopped
        command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
        ports:
            - "95:95"
            - "446:446"
